# Generated by Django 4.1.7 on 2023-09-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='country_code',
        ),
    ]
