# Generated by Django 4.1.7 on 2023-10-01 15:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country_code',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
