# Generated by Django 4.1.7 on 2023-08-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeandoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_office',
            name='region',
        ),
    ]
