# Generated by Django 4.1.7 on 2023-10-01 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_business_permit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bs_permit_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Permit Number'),
        ),
        migrations.AlterField(
            model_name='business',
            name='id_attachment',
            field=models.FileField(default='not available', upload_to=None, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='business',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='kra pin number'),
        ),
    ]
